"""
main.py — GigKavach FastAPI Application Entry Point
─────────────────────────────────────────────────────
This is the root of the backend. It:
  1. Creates the FastAPI app with metadata
  2. Registers all route modules (routers)
  3. Sets up CORS for the React frontend
  4. Starts the APScheduler background job for DCI polling (every 5 min)
  5. Provides the startup/shutdown lifecycle hooks

To run locally:
    uvicorn main:app --reload --port 3000

Production (Render.com):
    uvicorn main:app --host 0.0.0.0 --port $PORT

API Docs (auto-generated by FastAPI):
    http://localhost:3000/docs      ← Swagger UI (interactive)
    http://localhost:3000/redoc     ← ReDoc (clean reading)
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from contextlib import asynccontextmanager
import logging

from config.settings import settings
from api.routes.health import router as health_router
from api.routes.workers import router as workers_router
from api.routes.policies import router as policies_router
from api.dci import router as dci_router
from api.payouts import router as payouts_router
from api.fraud import router as fraud_router


# ─── Logging Setup ────────────────────────────────────────────────────────────
# All modules use logging.getLogger("gigkavach.<module>")
# This root setup ensures logs appear in console during development.
logging.basicConfig(
    level=logging.DEBUG if settings.APP_ENV == "development" else logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger("gigkavach.main")


# ─── Lifespan (Startup + Shutdown) ───────────────────────────────────────────
@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Modern FastAPI lifespan handler — replaces deprecated @app.on_event decorators.
    Code before `yield` runs on startup; code after runs on shutdown.
    """
    # ── STARTUP ──────────────────────────────────────────────────────────────
    logger.info("=" * 60)
    logger.info("  GigKavach API starting up...")
    logger.info(f"  Environment: {settings.APP_ENV}")
    logger.info("=" * 60)

    # Verify critical credentials are set (warn but don't crash — allows
    # teammates to run partial setups during development)
    if not settings.SUPABASE_URL:
        logger.warning("⚠️  SUPABASE_URL not set — database operations will fail")
    if not settings.TWILIO_ACCOUNT_SID:
        logger.warning("⚠️  TWILIO_ACCOUNT_SID not set — WhatsApp messages will fail")
    if not settings.TOMORROW_IO_API_KEY:
        logger.warning("⚠️  TOMORROW_IO_API_KEY not set — DCI weather component will use fallbacks")

    # ── Start APScheduler for Background Jobs ────────────────────────────────
    # Background jobs:
    # 1. DCI Engine — polls weather/AQI/social APIs every 5 minutes
    # 2. Claims Pipeline — processes pending claims every 5 minutes
    # 3. RSS Parser — fetches news articles every 1 hour
    # 4. DCI Archival — archives historical data daily at 2 AM UTC
    
    try:
        from cron.scheduler import configure_scheduler
        configure_scheduler()
        logger.info("✅ Background scheduler started (DCI, Claims, RSS, Archival)")

    except Exception as e:
        logger.error(f"⚠️  Failed to start scheduler: {e}")
        logger.warning("Continuing without background jobs...")

    logger.info("GigKavach API ready ✅")

    yield  # ← Application runs here

    # ── SHUTDOWN ─────────────────────────────────────────────────────────────
    logger.info("GigKavach API shutting down...")
    try:
        from cron.scheduler import stop_scheduler
        stop_scheduler()
    except Exception as e:
        logger.error(f"Error stopping scheduler: {e}")



# ─── FastAPI App Instance ─────────────────────────────────────────────────────
app = FastAPI(
    title="GigKavach API",
    description="""
## 🛡️ GigKavach — Zero-Touch Parametric Income Protection

Backend API for the GigKavach platform serving food delivery workers (Zomato/Swiggy).

### Core Components
- **DCI Engine** — Disruption Composite Index computed every 5 minutes per pin-code zone
- **WhatsApp Webhook** — Twilio integration for worker onboarding and notifications
- **Payout Pipeline** — Razorpay UPI test mode payouts triggered automatically
- **Fraud Detection** — Isolation Forest + 6-signal anti-spoofing layer

### Team Quadcore — DEVTrails 2026 (Guidewire)
- Varshit: Backend + DCI Engine
- Vijeth: ML Models + Fraud Detection
- V Saatwik: Frontend + Dashboard
- Sumukh Shandilya: WhatsApp Interface + API Integrations
    """,
    version="0.2.0",
    docs_url="/docs",
    redoc_url="/redoc",
    lifespan=lifespan,
)


# ─── CORS Middleware ──────────────────────────────────────────────────────────
# Required so the React frontend (Vite on :5173 or Vercel) can call this API.
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",    # Vite dev server (V Saatwik's frontend)
        "http://localhost:3000",    # Alternative React dev port
        "https://*.vercel.app",     # Production frontend on Vercel
        "*" if settings.APP_ENV == "development" else "",  # Open in dev
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ─── Route Registration ───────────────────────────────────────────────────────
# Each feature area has its own router in api/.
# Add new routers here as teammates build them.

app.include_router(health_router)
app.include_router(workers_router)   # POST /api/v1/register — Sumukh
app.include_router(policies_router)  # GET + PATCH /api/v1/policy/{id} — Sumukh
# app.include_router(worker_list_router)   # GET /api/workers — teammate compatibility
# app.include_router(worker_detail_router) # GET /api/worker/{worker_id} — teammate compatibility

# Fraud Detection (Vijeth)
app.include_router(fraud_router, prefix="/api/v1")

# DCI Engine (Varshit)
app.include_router(dci_router, prefix="/api/v1")

# Payouts & SLA (Sumukh)
app.include_router(payouts_router, prefix="/api/v1")

# TODO: Uncomment as each route module is built:
# app.include_router(whatsapp_router, prefix="/api/v1")   # Sumukh — Twilio webhook
# app.include_router(dashboard_router, prefix="/api/v1")  # V Saatwik — admin metrics


# ─── Root Redirect ────────────────────────────────────────────────────────────
@app.get("/", include_in_schema=False)
async def root():
    """Redirect root to API docs so teammates can explore endpoints easily"""
    from fastapi.responses import RedirectResponse
    return RedirectResponse(url="/docs")
