"""
main.py — GigKavach FastAPI Application Entry Point
─────────────────────────────────────────────────────
This is the root of the backend. It:
  1. Creates the FastAPI app with metadata
  2. Registers all route modules (routers)
  3. Sets up CORS for the React frontend
  4. Starts the APScheduler background job for DCI polling (every 5 min)
  5. Provides the startup/shutdown lifecycle hooks

To run locally:
    uvicorn main:app --reload --port 8000

Production (Render.com):
    uvicorn main:app --host 0.0.0.0 --port $PORT

API Docs (auto-generated by FastAPI):
    http://localhost:8000/docs      ← Swagger UI (interactive)
    http://localhost:8000/redoc     ← ReDoc (clean reading)
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from contextlib import asynccontextmanager
import logging

from config.settings import settings
# Task 10 Fix: modules live in api/, NOT api/routes/ — correcting all import paths
from api.health import router as health_router
from api.workers import router as workers_router
from api.policies import router as policies_router
from api.dci import router as dci_router
from api.payouts import router as payouts_router
from api.fraud import router as fraud_router       # Task 8: now active
from api.whatsapp import router as whatsapp_router


# ─── Logging Setup ────────────────────────────────────────────────────────────
# All modules use logging.getLogger("gigkavach.<module>")
# This root setup ensures logs appear in console during development.
logging.basicConfig(
    level=logging.DEBUG if settings.APP_ENV == "development" else logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger("gigkavach.main")


# ─── Lifespan (Startup + Shutdown) ───────────────────────────────────────────
@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Modern FastAPI lifespan handler — replaces deprecated @app.on_event decorators.
    Code before `yield` runs on startup; code after runs on shutdown.
    """
    # ── STARTUP ──────────────────────────────────────────────────────────────
    logger.info("=" * 60)
    logger.info("  GigKavach API starting up...")
    logger.info(f"  Environment: {settings.APP_ENV}")
    logger.info("=" * 60)

    # Verify critical credentials are set (warn but don't crash — allows
    # teammates to run partial setups during development)
    if not settings.SUPABASE_URL:
        logger.warning("⚠️  SUPABASE_URL not set — database operations will fail")
    if not settings.TWILIO_ACCOUNT_SID:
        logger.warning("⚠️  TWILIO_ACCOUNT_SID not set — WhatsApp messages will fail")
    if not settings.TOMORROW_IO_API_KEY:
        logger.warning("⚠️  TOMORROW_IO_API_KEY not set — DCI weather component will use fallbacks")

    # ── Start APScheduler for DCI Engine ─────────────────────────────────────
    # The DCI engine polls weather/AQI/social APIs every 5 minutes and
    # updates the DCI score for all active zones.
    # We import lazily here so this file doesn't crash if DCI engine isn't built yet.
    try:
        from apscheduler.schedulers.asyncio import AsyncIOScheduler

        scheduler = AsyncIOScheduler()

        # (Varshit): Uncommented and wired to cron poller
        from cron.dci_poller import run_dci_cycle
        from cron.settlement_service import run_daily_settlement

        scheduler.add_job(
            run_dci_cycle,
            "interval",
            seconds=settings.DCI_POLL_INTERVAL_SECONDS,
            id="dci_engine",
            name="DCI Engine Poll",
        )

        # ── Daily Settlement Execution 11:55 PM (Image #5 Requirement) ───────────
        scheduler.add_job(
            run_daily_settlement,
            "cron",
            hour=23,
            minute=55,
            id="daily_settlement",
            name="End of Day Payout Settlement",
        )

        # Task 11: Replace dummy heartbeat with the real claims pipeline job.
        # The claims pipeline runs every 5 min alongside the DCI engine.
        from cron.claims_trigger import run_claims_pipeline
        scheduler.add_job(
            run_claims_pipeline,
            "interval",
            seconds=settings.DCI_POLL_INTERVAL_SECONDS,  # same 5-min cadence
            id="claims_pipeline",
            name="Claims Processing Pipeline",
        )

        scheduler.start()
        app.state.scheduler = scheduler
        logger.info(f"APScheduler started | DCI poll every {settings.DCI_POLL_INTERVAL_SECONDS}s")

    except Exception as e:
        logger.error(f"Failed to start APScheduler: {e}")

    logger.info("GigKavach API ready ✅")

    yield  # ← Application runs here

    # ── SHUTDOWN ─────────────────────────────────────────────────────────────
    logger.info("GigKavach API shutting down...")
    if hasattr(app.state, "scheduler"):
        app.state.scheduler.shutdown(wait=False)
        logger.info("APScheduler stopped")



# ─── FastAPI App Instance ─────────────────────────────────────────────────────
app = FastAPI(
    title="GigKavach API",
    description="""
## 🛡️ GigKavach — Zero-Touch Parametric Income Protection

Backend API for the GigKavach platform serving food delivery workers (Zomato/Swiggy).

### Core Components
- **DCI Engine** — Disruption Composite Index computed every 5 minutes per pin-code zone
- **WhatsApp Webhook** — Twilio integration for worker onboarding and notifications
- **Payout Pipeline** — Razorpay UPI test mode payouts triggered automatically
- **Fraud Detection** — Isolation Forest + 6-signal anti-spoofing layer

### Team Quadcore — DEVTrails 2026 (Guidewire)
- Varshit: Backend + DCI Engine
- Vijeth: ML Models + Fraud Detection
- V Saatwik: Frontend + Dashboard
- Sumukh Shandilya: WhatsApp Interface + API Integrations
    """,
    version="0.2.0",
    docs_url="/docs",
    redoc_url="/redoc",
    lifespan=lifespan,
)


# ─── CORS Middleware ──────────────────────────────────────────────────────────
# Required so the React frontend (Vite on :5173 or Vercel) can call this API.
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",    # Vite dev server (V Saatwik's frontend)
        "http://localhost:3000",    # Alternative React dev port
        "https://*.vercel.app",     # Production frontend on Vercel
        "*" if settings.APP_ENV == "development" else "",  # Open in dev
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ─── Route Registration ───────────────────────────────────────────────────────
# Each feature area has its own router in api/routes/.
# Add new routers here as teammates build them.

app.include_router(health_router)
app.include_router(workers_router)    # POST /api/v1/register — Sumukh
app.include_router(policies_router)   # GET + PATCH /api/v1/policy/{id} — Sumukh
app.include_router(dci_router, prefix="/api/v1")           # Varshit — DCI engine
app.include_router(whatsapp_router, prefix="/api")          # Sumukh — Twilio webhook at /api/whatsapp/webhook
app.include_router(payouts_router, prefix="/api/v1")        # Sumukh — payout calculation
app.include_router(fraud_router, prefix="/api/v1")          # Vijeth — fraud assessment (Task 8)
# TODO: app.include_router(dashboard_router, prefix="/api/v1")  # V Saatwik — admin metrics


# ─── Root Redirect ────────────────────────────────────────────────────────────
@app.get("/", include_in_schema=False)
async def root():
    """Redirect root to API docs so teammates can explore endpoints easily"""
    from fastapi.responses import RedirectResponse
    return RedirectResponse(url="/docs")

from api.dci_alerts import router as dci_alerts_router

app.include_router(dci_alerts_router, prefix="/api/v1")
from api.payouts import router as payouts_router

app.include_router(payouts_router)

from api import dci_Dashboard

app.include_router(dci_Dashboard.router)

from api import workers_Dashboard

app.include_router(workers_Dashboard.router, prefix="/api")

from api.worker_list import router as workers_list_router
app.include_router(workers_list_router, prefix="/api")

from api.worker_detail import router as workers_detail_router
app.include_router(workers_detail_router, prefix="/api")